### ISSUE TITLE
xcode project does not define target "Runner"

### ISSUE THREAD

**Issue by donaldjr** [TylerSustare/flutter-score-keeper#25]
```
The Xcode project does not define target "Runner" which is needed by Flutter
tooling.
Open Xcode to fix the problem:
  open ios/Runner.xcworkspace
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```

Getting this error right now when running `flutter run`.

Thing is I created a new app and ran `flutter run` and it opened on the iPhone with no problem.

I followed [this](https://stackoverflow.com/questions/55888639/getting-error-while-running-flutter-project-in-simulator-in-debug-mode) stackoverflow and got it working by manually opening up the `ios/Runner.xcworkspace` and fixing the build issues. After that I can run the app from xcode but it still returns the same error for `flutter run`

I haven't found much of anything else on this issue but I can run in it in android so I can work from there.

**Comment by TylerSustare** [comment]
@donaldjr this should be fixed now. LMK if it's good to close.

**Comment by donaldjr** [comment]
yea we good now
